title: "Open Source University, la plateforme numérique en source ouverte des Universités & des Écoles"
url: https://www.osuny.org
domain: osuny.org

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "features"
    values:
      layout: "feature"
  -
    scope:
      path: ""
      type: "categories"
    values:
      layout: "category"

collections:
  pages:
    output: true
  categories:
    output: true
    permalink: :slug
  features:
    output: true
