title: "Open Source University, la plateforme numérique en source ouverte des Universités & des Écoles"
url: https://www.osuny.org
domain: osuny.org

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

collections:
  pages:
    output: true
