title: "Open Source University, la plateforme numérique en source ouverte des Universités & des Écoles"
url: https://www.osuny.org
domain: osuny.org

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "features"
    values:
      layout: "feature"
  -
    scope:
      path: ""
      type: "categories"
    values:
      layout: "category"

collections:
  pages:
    output: true
  categories:
    output: true
    permalink: :slug
  features:
    output: true

plugins:
  - jekyll-minifier
  - jekyll-sitemap

sass:
  style: compressed
  load_paths:
      - _sass
      - node_modules

jekyll-minifier:
  remove_spaces_inside_tags: true
  remove_multi_spaces: true
  remove_intertag_spaces: false
  remove_comments: true
  compress_css: false
  compress_javascript: true

picture:
  ignore_missing_images: true
